# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/2014_srcnn_bn.ipynb (unless otherwise specified).

__all__ = ['SRCNN_BN']

# Cell
from fastai import *
from fastai.vision import *
from fastai.callbacks import *

# Cell
class SRCNN_BN(nn.Module):
    """ Image super-resolution using deep convolutional networks """

    def __init__(self):
        super(SRCNN_BN, self).__init__()
        self.conv1 = conv_layer(ni=3, nf=64, ks=9, stride=1, padding=4)
        self.conv2 = conv_layer(ni=64, nf=32, ks=1, stride=1, padding=0)
        self.conv3 = conv_layer(ni=32, nf=3, ks=5, stride=1, padding=2, use_activ=False)

    def forward(self, x):
        h = self.conv1(x)
        h = self.conv2(h)
        return self.conv3(h)